//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BCC_DOTNET_LMSModel", "fk_bookid", "tblBook", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Library_Management_System.Data.tblBook), "tblBooksIssued", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Library_Management_System.Data.tblBooksIssued), true)]
[assembly: EdmRelationshipAttribute("BCC_DOTNET_LMSModel", "fk_logid", "tblStudentInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Library_Management_System.Data.tblStudentInfo), "tblStudentLogin", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Library_Management_System.Data.tblStudentLogin), true)]
[assembly: EdmRelationshipAttribute("BCC_DOTNET_LMSModel", "fk_stuid", "tblStudentInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Library_Management_System.Data.tblStudentInfo), "tblBooksIssued", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Library_Management_System.Data.tblBooksIssued), true)]
[assembly: EdmRelationshipAttribute("BCC_DOTNET_LMSModel", "fk_loginid", "tblTeacherInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Library_Management_System.Data.tblTeacherInfo), "tblTeacherLogin", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Library_Management_System.Data.tblTeacherLogin), true)]

#endregion

namespace Library_Management_System.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BCC_DOTNET_LMSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BCC_DOTNET_LMSEntities object using the connection string found in the 'BCC_DOTNET_LMSEntities' section of the application configuration file.
        /// </summary>
        public BCC_DOTNET_LMSEntities() : base("name=BCC_DOTNET_LMSEntities", "BCC_DOTNET_LMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BCC_DOTNET_LMSEntities object.
        /// </summary>
        public BCC_DOTNET_LMSEntities(string connectionString) : base(connectionString, "BCC_DOTNET_LMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BCC_DOTNET_LMSEntities object.
        /// </summary>
        public BCC_DOTNET_LMSEntities(EntityConnection connection) : base(connection, "BCC_DOTNET_LMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblBook> tblBooks
        {
            get
            {
                if ((_tblBooks == null))
                {
                    _tblBooks = base.CreateObjectSet<tblBook>("tblBooks");
                }
                return _tblBooks;
            }
        }
        private ObjectSet<tblBook> _tblBooks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblStudentInfo> tblStudentInfoes
        {
            get
            {
                if ((_tblStudentInfoes == null))
                {
                    _tblStudentInfoes = base.CreateObjectSet<tblStudentInfo>("tblStudentInfoes");
                }
                return _tblStudentInfoes;
            }
        }
        private ObjectSet<tblStudentInfo> _tblStudentInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTeacherInfo> tblTeacherInfoes
        {
            get
            {
                if ((_tblTeacherInfoes == null))
                {
                    _tblTeacherInfoes = base.CreateObjectSet<tblTeacherInfo>("tblTeacherInfoes");
                }
                return _tblTeacherInfoes;
            }
        }
        private ObjectSet<tblTeacherInfo> _tblTeacherInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblBooksIssued> tblBooksIssueds
        {
            get
            {
                if ((_tblBooksIssueds == null))
                {
                    _tblBooksIssueds = base.CreateObjectSet<tblBooksIssued>("tblBooksIssueds");
                }
                return _tblBooksIssueds;
            }
        }
        private ObjectSet<tblBooksIssued> _tblBooksIssueds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblStudentLogin> tblStudentLogins
        {
            get
            {
                if ((_tblStudentLogins == null))
                {
                    _tblStudentLogins = base.CreateObjectSet<tblStudentLogin>("tblStudentLogins");
                }
                return _tblStudentLogins;
            }
        }
        private ObjectSet<tblStudentLogin> _tblStudentLogins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTeacherLogin> tblTeacherLogins
        {
            get
            {
                if ((_tblTeacherLogins == null))
                {
                    _tblTeacherLogins = base.CreateObjectSet<tblTeacherLogin>("tblTeacherLogins");
                }
                return _tblTeacherLogins;
            }
        }
        private ObjectSet<tblTeacherLogin> _tblTeacherLogins;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblBooks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblBooks(tblBook tblBook)
        {
            base.AddObject("tblBooks", tblBook);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblStudentInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblStudentInfoes(tblStudentInfo tblStudentInfo)
        {
            base.AddObject("tblStudentInfoes", tblStudentInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTeacherInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTeacherInfoes(tblTeacherInfo tblTeacherInfo)
        {
            base.AddObject("tblTeacherInfoes", tblTeacherInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblBooksIssueds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblBooksIssueds(tblBooksIssued tblBooksIssued)
        {
            base.AddObject("tblBooksIssueds", tblBooksIssued);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblStudentLogins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblStudentLogins(tblStudentLogin tblStudentLogin)
        {
            base.AddObject("tblStudentLogins", tblStudentLogin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTeacherLogins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTeacherLogins(tblTeacherLogin tblTeacherLogin)
        {
            base.AddObject("tblTeacherLogins", tblTeacherLogin);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="reg_id">No Metadata Documentation available.</param>
        /// <param name="branch">No Metadata Documentation available.</param>
        /// <param name="section">No Metadata Documentation available.</param>
        /// <param name="semester">No Metadata Documentation available.</param>
        /// <param name="yoa">No Metadata Documentation available.</param>
        public int sp_insertStudentInfo(Nullable<global::System.Int32> reg_id, global::System.String branch, global::System.String section, global::System.String semester, Nullable<global::System.Int32> yoa)
        {
            ObjectParameter reg_idParameter;
            if (reg_id.HasValue)
            {
                reg_idParameter = new ObjectParameter("reg_id", reg_id);
            }
            else
            {
                reg_idParameter = new ObjectParameter("reg_id", typeof(global::System.Int32));
            }
    
            ObjectParameter branchParameter;
            if (branch != null)
            {
                branchParameter = new ObjectParameter("branch", branch);
            }
            else
            {
                branchParameter = new ObjectParameter("branch", typeof(global::System.String));
            }
    
            ObjectParameter sectionParameter;
            if (section != null)
            {
                sectionParameter = new ObjectParameter("section", section);
            }
            else
            {
                sectionParameter = new ObjectParameter("section", typeof(global::System.String));
            }
    
            ObjectParameter semesterParameter;
            if (semester != null)
            {
                semesterParameter = new ObjectParameter("semester", semester);
            }
            else
            {
                semesterParameter = new ObjectParameter("semester", typeof(global::System.String));
            }
    
            ObjectParameter yoaParameter;
            if (yoa.HasValue)
            {
                yoaParameter = new ObjectParameter("yoa", yoa);
            }
            else
            {
                yoaParameter = new ObjectParameter("yoa", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("sp_insertStudentInfo", reg_idParameter, branchParameter, sectionParameter, semesterParameter, yoaParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="reg_id">No Metadata Documentation available.</param>
        /// <param name="libid">No Metadata Documentation available.</param>
        public int sp_libraryID(Nullable<global::System.Int32> reg_id, ObjectParameter libid)
        {
            ObjectParameter reg_idParameter;
            if (reg_id.HasValue)
            {
                reg_idParameter = new ObjectParameter("reg_id", reg_id);
            }
            else
            {
                reg_idParameter = new ObjectParameter("reg_id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("sp_libraryID", reg_idParameter, libid);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="log_id">No Metadata Documentation available.</param>
        /// <param name="username">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        public int sp_insertSTDLogin(Nullable<global::System.Int32> log_id, global::System.String username, global::System.String password)
        {
            ObjectParameter log_idParameter;
            if (log_id.HasValue)
            {
                log_idParameter = new ObjectParameter("log_id", log_id);
            }
            else
            {
                log_idParameter = new ObjectParameter("log_id", typeof(global::System.Int32));
            }
    
            ObjectParameter usernameParameter;
            if (username != null)
            {
                usernameParameter = new ObjectParameter("username", username);
            }
            else
            {
                usernameParameter = new ObjectParameter("username", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("password", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("sp_insertSTDLogin", log_idParameter, usernameParameter, passwordParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="title">No Metadata Documentation available.</param>
        /// <param name="author">No Metadata Documentation available.</param>
        /// <param name="publication">No Metadata Documentation available.</param>
        /// <param name="subject">No Metadata Documentation available.</param>
        /// <param name="no_0f_copies">No Metadata Documentation available.</param>
        /// <param name="cover_pic">No Metadata Documentation available.</param>
        public int sp_addBooks(global::System.String title, global::System.String author, global::System.String publication, global::System.String subject, Nullable<global::System.Int32> no_0f_copies, global::System.Byte[] cover_pic)
        {
            ObjectParameter titleParameter;
            if (title != null)
            {
                titleParameter = new ObjectParameter("title", title);
            }
            else
            {
                titleParameter = new ObjectParameter("title", typeof(global::System.String));
            }
    
            ObjectParameter authorParameter;
            if (author != null)
            {
                authorParameter = new ObjectParameter("author", author);
            }
            else
            {
                authorParameter = new ObjectParameter("author", typeof(global::System.String));
            }
    
            ObjectParameter publicationParameter;
            if (publication != null)
            {
                publicationParameter = new ObjectParameter("publication", publication);
            }
            else
            {
                publicationParameter = new ObjectParameter("publication", typeof(global::System.String));
            }
    
            ObjectParameter subjectParameter;
            if (subject != null)
            {
                subjectParameter = new ObjectParameter("subject", subject);
            }
            else
            {
                subjectParameter = new ObjectParameter("subject", typeof(global::System.String));
            }
    
            ObjectParameter no_0f_copiesParameter;
            if (no_0f_copies.HasValue)
            {
                no_0f_copiesParameter = new ObjectParameter("no_0f_copies", no_0f_copies);
            }
            else
            {
                no_0f_copiesParameter = new ObjectParameter("no_0f_copies", typeof(global::System.Int32));
            }
    
            ObjectParameter cover_picParameter;
            if (cover_pic != null)
            {
                cover_picParameter = new ObjectParameter("cover_pic", cover_pic);
            }
            else
            {
                cover_picParameter = new ObjectParameter("cover_pic", typeof(global::System.Byte[]));
            }
    
            return base.ExecuteFunction("sp_addBooks", titleParameter, authorParameter, publicationParameter, subjectParameter, no_0f_copiesParameter, cover_picParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="login_id">No Metadata Documentation available.</param>
        /// <param name="username">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        public int sp_insertTCHRLogin(Nullable<global::System.Int32> login_id, global::System.String username, global::System.String password)
        {
            ObjectParameter login_idParameter;
            if (login_id.HasValue)
            {
                login_idParameter = new ObjectParameter("login_id", login_id);
            }
            else
            {
                login_idParameter = new ObjectParameter("login_id", typeof(global::System.Int32));
            }
    
            ObjectParameter usernameParameter;
            if (username != null)
            {
                usernameParameter = new ObjectParameter("username", username);
            }
            else
            {
                usernameParameter = new ObjectParameter("username", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("password", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("sp_insertTCHRLogin", login_idParameter, usernameParameter, passwordParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="book_id">No Metadata Documentation available.</param>
        /// <param name="student_id">No Metadata Documentation available.</param>
        /// <param name="issue_date">No Metadata Documentation available.</param>
        /// <param name="return_date">No Metadata Documentation available.</param>
        /// <param name="no_of_books">No Metadata Documentation available.</param>
        public int sp_issueBooks(Nullable<global::System.Int32> book_id, Nullable<global::System.Int32> student_id, Nullable<global::System.DateTime> issue_date, Nullable<global::System.DateTime> return_date, Nullable<global::System.Int32> no_of_books)
        {
            ObjectParameter book_idParameter;
            if (book_id.HasValue)
            {
                book_idParameter = new ObjectParameter("book_id", book_id);
            }
            else
            {
                book_idParameter = new ObjectParameter("book_id", typeof(global::System.Int32));
            }
    
            ObjectParameter student_idParameter;
            if (student_id.HasValue)
            {
                student_idParameter = new ObjectParameter("student_id", student_id);
            }
            else
            {
                student_idParameter = new ObjectParameter("student_id", typeof(global::System.Int32));
            }
    
            ObjectParameter issue_dateParameter;
            if (issue_date.HasValue)
            {
                issue_dateParameter = new ObjectParameter("issue_date", issue_date);
            }
            else
            {
                issue_dateParameter = new ObjectParameter("issue_date", typeof(global::System.DateTime));
            }
    
            ObjectParameter return_dateParameter;
            if (return_date.HasValue)
            {
                return_dateParameter = new ObjectParameter("return_date", return_date);
            }
            else
            {
                return_dateParameter = new ObjectParameter("return_date", typeof(global::System.DateTime));
            }
    
            ObjectParameter no_of_booksParameter;
            if (no_of_books.HasValue)
            {
                no_of_booksParameter = new ObjectParameter("no_of_books", no_of_books);
            }
            else
            {
                no_of_booksParameter = new ObjectParameter("no_of_books", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("sp_issueBooks", book_idParameter, student_idParameter, issue_dateParameter, return_dateParameter, no_of_booksParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="book_id">No Metadata Documentation available.</param>
        /// <param name="student_id">No Metadata Documentation available.</param>
        /// <param name="no_of_books">No Metadata Documentation available.</param>
        public int sp_returnBooks(Nullable<global::System.Int32> book_id, Nullable<global::System.Int32> student_id, Nullable<global::System.Int32> no_of_books)
        {
            ObjectParameter book_idParameter;
            if (book_id.HasValue)
            {
                book_idParameter = new ObjectParameter("book_id", book_id);
            }
            else
            {
                book_idParameter = new ObjectParameter("book_id", typeof(global::System.Int32));
            }
    
            ObjectParameter student_idParameter;
            if (student_id.HasValue)
            {
                student_idParameter = new ObjectParameter("student_id", student_id);
            }
            else
            {
                student_idParameter = new ObjectParameter("student_id", typeof(global::System.Int32));
            }
    
            ObjectParameter no_of_booksParameter;
            if (no_of_books.HasValue)
            {
                no_of_booksParameter = new ObjectParameter("no_of_books", no_of_books);
            }
            else
            {
                no_of_booksParameter = new ObjectParameter("no_of_books", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("sp_returnBooks", book_idParameter, student_idParameter, no_of_booksParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="tid">No Metadata Documentation available.</param>
        public int sp_teacherID(global::System.String name, ObjectParameter tid)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("name", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("sp_teacherID", nameParameter, tid);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="designation">No Metadata Documentation available.</param>
        /// <param name="branch">No Metadata Documentation available.</param>
        /// <param name="contact_no">No Metadata Documentation available.</param>
        /// <param name="lectures">No Metadata Documentation available.</param>
        public int sp_insertTeacherInfo(global::System.String name, global::System.String designation, global::System.String branch, global::System.String contact_no, global::System.String lectures)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("name", typeof(global::System.String));
            }
    
            ObjectParameter designationParameter;
            if (designation != null)
            {
                designationParameter = new ObjectParameter("designation", designation);
            }
            else
            {
                designationParameter = new ObjectParameter("designation", typeof(global::System.String));
            }
    
            ObjectParameter branchParameter;
            if (branch != null)
            {
                branchParameter = new ObjectParameter("branch", branch);
            }
            else
            {
                branchParameter = new ObjectParameter("branch", typeof(global::System.String));
            }
    
            ObjectParameter contact_noParameter;
            if (contact_no != null)
            {
                contact_noParameter = new ObjectParameter("contact_no", contact_no);
            }
            else
            {
                contact_noParameter = new ObjectParameter("contact_no", typeof(global::System.String));
            }
    
            ObjectParameter lecturesParameter;
            if (lectures != null)
            {
                lecturesParameter = new ObjectParameter("lectures", lectures);
            }
            else
            {
                lecturesParameter = new ObjectParameter("lectures", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("sp_insertTeacherInfo", nameParameter, designationParameter, branchParameter, contact_noParameter, lecturesParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<global::System.String> sp_selectBookAuthor()
        {
            return base.ExecuteFunction<global::System.String>("sp_selectBookAuthor");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<global::System.String> sp_selectBookTitle()
        {
            return base.ExecuteFunction<global::System.String>("sp_selectBookTitle");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="search">No Metadata Documentation available.</param>
        public int sp_searchBooksByAuthor(global::System.String search)
        {
            ObjectParameter searchParameter;
            if (search != null)
            {
                searchParameter = new ObjectParameter("search", search);
            }
            else
            {
                searchParameter = new ObjectParameter("search", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("sp_searchBooksByAuthor", searchParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="search">No Metadata Documentation available.</param>
        public int sp_searchBooksByName(global::System.String search)
        {
            ObjectParameter searchParameter;
            if (search != null)
            {
                searchParameter = new ObjectParameter("search", search);
            }
            else
            {
                searchParameter = new ObjectParameter("search", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("sp_searchBooksByName", searchParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCC_DOTNET_LMSModel", Name="tblBook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblBook : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblBook object.
        /// </summary>
        /// <param name="code">Initial value of the code property.</param>
        public static tblBook CreatetblBook(global::System.Int32 code)
        {
            tblBook tblBook = new tblBook();
            tblBook.code = code;
            return tblBook;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code
        {
            get
            {
                return _code;
            }
            set
            {
                if (_code != value)
                {
                    OncodeChanging(value);
                    ReportPropertyChanging("code");
                    _code = StructuralObject.SetValidValue(value, "code");
                    ReportPropertyChanged("code");
                    OncodeChanged();
                }
            }
        }
        private global::System.Int32 _code;
        partial void OncodeChanging(global::System.Int32 value);
        partial void OncodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, true, "author");
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String publication
        {
            get
            {
                return _publication;
            }
            set
            {
                OnpublicationChanging(value);
                ReportPropertyChanging("publication");
                _publication = StructuralObject.SetValidValue(value, true, "publication");
                ReportPropertyChanged("publication");
                OnpublicationChanged();
            }
        }
        private global::System.String _publication;
        partial void OnpublicationChanging(global::System.String value);
        partial void OnpublicationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String subject
        {
            get
            {
                return _subject;
            }
            set
            {
                OnsubjectChanging(value);
                ReportPropertyChanging("subject");
                _subject = StructuralObject.SetValidValue(value, true, "subject");
                ReportPropertyChanged("subject");
                OnsubjectChanged();
            }
        }
        private global::System.String _subject;
        partial void OnsubjectChanging(global::System.String value);
        partial void OnsubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> no_of_copies
        {
            get
            {
                return _no_of_copies;
            }
            set
            {
                Onno_of_copiesChanging(value);
                ReportPropertyChanging("no_of_copies");
                _no_of_copies = StructuralObject.SetValidValue(value, "no_of_copies");
                ReportPropertyChanged("no_of_copies");
                Onno_of_copiesChanged();
            }
        }
        private Nullable<global::System.Int32> _no_of_copies;
        partial void Onno_of_copiesChanging(Nullable<global::System.Int32> value);
        partial void Onno_of_copiesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] cover_pic
        {
            get
            {
                return StructuralObject.GetValidValue(_cover_pic);
            }
            set
            {
                Oncover_picChanging(value);
                ReportPropertyChanging("cover_pic");
                _cover_pic = StructuralObject.SetValidValue(value, true, "cover_pic");
                ReportPropertyChanged("cover_pic");
                Oncover_picChanged();
            }
        }
        private global::System.Byte[] _cover_pic;
        partial void Oncover_picChanging(global::System.Byte[] value);
        partial void Oncover_picChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCC_DOTNET_LMSModel", "fk_bookid", "tblBooksIssued")]
        public EntityCollection<tblBooksIssued> tblBooksIssueds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblBooksIssued>("BCC_DOTNET_LMSModel.fk_bookid", "tblBooksIssued");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblBooksIssued>("BCC_DOTNET_LMSModel.fk_bookid", "tblBooksIssued", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCC_DOTNET_LMSModel", Name="tblBooksIssued")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblBooksIssued : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblBooksIssued object.
        /// </summary>
        /// <param name="bookid">Initial value of the bookid property.</param>
        /// <param name="stuid">Initial value of the stuid property.</param>
        public static tblBooksIssued CreatetblBooksIssued(global::System.Int32 bookid, global::System.Int32 stuid)
        {
            tblBooksIssued tblBooksIssued = new tblBooksIssued();
            tblBooksIssued.bookid = bookid;
            tblBooksIssued.stuid = stuid;
            return tblBooksIssued;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bookid
        {
            get
            {
                return _bookid;
            }
            set
            {
                if (_bookid != value)
                {
                    OnbookidChanging(value);
                    ReportPropertyChanging("bookid");
                    _bookid = StructuralObject.SetValidValue(value, "bookid");
                    ReportPropertyChanged("bookid");
                    OnbookidChanged();
                }
            }
        }
        private global::System.Int32 _bookid;
        partial void OnbookidChanging(global::System.Int32 value);
        partial void OnbookidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stuid
        {
            get
            {
                return _stuid;
            }
            set
            {
                if (_stuid != value)
                {
                    OnstuidChanging(value);
                    ReportPropertyChanging("stuid");
                    _stuid = StructuralObject.SetValidValue(value, "stuid");
                    ReportPropertyChanged("stuid");
                    OnstuidChanged();
                }
            }
        }
        private global::System.Int32 _stuid;
        partial void OnstuidChanging(global::System.Int32 value);
        partial void OnstuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> issue_date
        {
            get
            {
                return _issue_date;
            }
            set
            {
                Onissue_dateChanging(value);
                ReportPropertyChanging("issue_date");
                _issue_date = StructuralObject.SetValidValue(value, "issue_date");
                ReportPropertyChanged("issue_date");
                Onissue_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _issue_date;
        partial void Onissue_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onissue_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> return_date
        {
            get
            {
                return _return_date;
            }
            set
            {
                Onreturn_dateChanging(value);
                ReportPropertyChanging("return_date");
                _return_date = StructuralObject.SetValidValue(value, "return_date");
                ReportPropertyChanged("return_date");
                Onreturn_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _return_date;
        partial void Onreturn_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onreturn_dateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCC_DOTNET_LMSModel", "fk_bookid", "tblBook")]
        public tblBook tblBook
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblBook>("BCC_DOTNET_LMSModel.fk_bookid", "tblBook").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblBook>("BCC_DOTNET_LMSModel.fk_bookid", "tblBook").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblBook> tblBookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblBook>("BCC_DOTNET_LMSModel.fk_bookid", "tblBook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblBook>("BCC_DOTNET_LMSModel.fk_bookid", "tblBook", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCC_DOTNET_LMSModel", "fk_stuid", "tblStudentInfo")]
        public tblStudentInfo tblStudentInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudentInfo>("BCC_DOTNET_LMSModel.fk_stuid", "tblStudentInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudentInfo>("BCC_DOTNET_LMSModel.fk_stuid", "tblStudentInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblStudentInfo> tblStudentInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudentInfo>("BCC_DOTNET_LMSModel.fk_stuid", "tblStudentInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblStudentInfo>("BCC_DOTNET_LMSModel.fk_stuid", "tblStudentInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCC_DOTNET_LMSModel", Name="tblStudentInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblStudentInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblStudentInfo object.
        /// </summary>
        /// <param name="libid">Initial value of the libid property.</param>
        public static tblStudentInfo CreatetblStudentInfo(global::System.Int32 libid)
        {
            tblStudentInfo tblStudentInfo = new tblStudentInfo();
            tblStudentInfo.libid = libid;
            return tblStudentInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 libid
        {
            get
            {
                return _libid;
            }
            set
            {
                if (_libid != value)
                {
                    OnlibidChanging(value);
                    ReportPropertyChanging("libid");
                    _libid = StructuralObject.SetValidValue(value, "libid");
                    ReportPropertyChanged("libid");
                    OnlibidChanged();
                }
            }
        }
        private global::System.Int32 _libid;
        partial void OnlibidChanging(global::System.Int32 value);
        partial void OnlibidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> regno
        {
            get
            {
                return _regno;
            }
            set
            {
                OnregnoChanging(value);
                ReportPropertyChanging("regno");
                _regno = StructuralObject.SetValidValue(value, "regno");
                ReportPropertyChanged("regno");
                OnregnoChanged();
            }
        }
        private Nullable<global::System.Int32> _regno;
        partial void OnregnoChanging(Nullable<global::System.Int32> value);
        partial void OnregnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String branch
        {
            get
            {
                return _branch;
            }
            set
            {
                OnbranchChanging(value);
                ReportPropertyChanging("branch");
                _branch = StructuralObject.SetValidValue(value, true, "branch");
                ReportPropertyChanged("branch");
                OnbranchChanged();
            }
        }
        private global::System.String _branch;
        partial void OnbranchChanging(global::System.String value);
        partial void OnbranchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String section
        {
            get
            {
                return _section;
            }
            set
            {
                OnsectionChanging(value);
                ReportPropertyChanging("section");
                _section = StructuralObject.SetValidValue(value, true, "section");
                ReportPropertyChanged("section");
                OnsectionChanged();
            }
        }
        private global::System.String _section;
        partial void OnsectionChanging(global::System.String value);
        partial void OnsectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String semester
        {
            get
            {
                return _semester;
            }
            set
            {
                OnsemesterChanging(value);
                ReportPropertyChanging("semester");
                _semester = StructuralObject.SetValidValue(value, true, "semester");
                ReportPropertyChanged("semester");
                OnsemesterChanged();
            }
        }
        private global::System.String _semester;
        partial void OnsemesterChanging(global::System.String value);
        partial void OnsemesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> year_of_admission
        {
            get
            {
                return _year_of_admission;
            }
            set
            {
                Onyear_of_admissionChanging(value);
                ReportPropertyChanging("year_of_admission");
                _year_of_admission = StructuralObject.SetValidValue(value, "year_of_admission");
                ReportPropertyChanged("year_of_admission");
                Onyear_of_admissionChanged();
            }
        }
        private Nullable<global::System.Int32> _year_of_admission;
        partial void Onyear_of_admissionChanging(Nullable<global::System.Int32> value);
        partial void Onyear_of_admissionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCC_DOTNET_LMSModel", "fk_logid", "tblStudentLogin")]
        public tblStudentLogin tblStudentLogin
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudentLogin>("BCC_DOTNET_LMSModel.fk_logid", "tblStudentLogin").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudentLogin>("BCC_DOTNET_LMSModel.fk_logid", "tblStudentLogin").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblStudentLogin> tblStudentLoginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudentLogin>("BCC_DOTNET_LMSModel.fk_logid", "tblStudentLogin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblStudentLogin>("BCC_DOTNET_LMSModel.fk_logid", "tblStudentLogin", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCC_DOTNET_LMSModel", "fk_stuid", "tblBooksIssued")]
        public EntityCollection<tblBooksIssued> tblBooksIssueds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblBooksIssued>("BCC_DOTNET_LMSModel.fk_stuid", "tblBooksIssued");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblBooksIssued>("BCC_DOTNET_LMSModel.fk_stuid", "tblBooksIssued", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCC_DOTNET_LMSModel", Name="tblStudentLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblStudentLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblStudentLogin object.
        /// </summary>
        /// <param name="logid">Initial value of the logid property.</param>
        public static tblStudentLogin CreatetblStudentLogin(global::System.Int32 logid)
        {
            tblStudentLogin tblStudentLogin = new tblStudentLogin();
            tblStudentLogin.logid = logid;
            return tblStudentLogin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 logid
        {
            get
            {
                return _logid;
            }
            set
            {
                if (_logid != value)
                {
                    OnlogidChanging(value);
                    ReportPropertyChanging("logid");
                    _logid = StructuralObject.SetValidValue(value, "logid");
                    ReportPropertyChanged("logid");
                    OnlogidChanged();
                }
            }
        }
        private global::System.Int32 _logid;
        partial void OnlogidChanging(global::System.Int32 value);
        partial void OnlogidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> number_of_books
        {
            get
            {
                return _number_of_books;
            }
            set
            {
                Onnumber_of_booksChanging(value);
                ReportPropertyChanging("number_of_books");
                _number_of_books = StructuralObject.SetValidValue(value, "number_of_books");
                ReportPropertyChanged("number_of_books");
                Onnumber_of_booksChanged();
            }
        }
        private Nullable<global::System.Int32> _number_of_books;
        partial void Onnumber_of_booksChanging(Nullable<global::System.Int32> value);
        partial void Onnumber_of_booksChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCC_DOTNET_LMSModel", "fk_logid", "tblStudentInfo")]
        public tblStudentInfo tblStudentInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudentInfo>("BCC_DOTNET_LMSModel.fk_logid", "tblStudentInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudentInfo>("BCC_DOTNET_LMSModel.fk_logid", "tblStudentInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblStudentInfo> tblStudentInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblStudentInfo>("BCC_DOTNET_LMSModel.fk_logid", "tblStudentInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblStudentInfo>("BCC_DOTNET_LMSModel.fk_logid", "tblStudentInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCC_DOTNET_LMSModel", Name="tblTeacherInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTeacherInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTeacherInfo object.
        /// </summary>
        /// <param name="tid">Initial value of the tid property.</param>
        public static tblTeacherInfo CreatetblTeacherInfo(global::System.Int32 tid)
        {
            tblTeacherInfo tblTeacherInfo = new tblTeacherInfo();
            tblTeacherInfo.tid = tid;
            return tblTeacherInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tid
        {
            get
            {
                return _tid;
            }
            set
            {
                if (_tid != value)
                {
                    OntidChanging(value);
                    ReportPropertyChanging("tid");
                    _tid = StructuralObject.SetValidValue(value, "tid");
                    ReportPropertyChanged("tid");
                    OntidChanged();
                }
            }
        }
        private global::System.Int32 _tid;
        partial void OntidChanging(global::System.Int32 value);
        partial void OntidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String designation
        {
            get
            {
                return _designation;
            }
            set
            {
                OndesignationChanging(value);
                ReportPropertyChanging("designation");
                _designation = StructuralObject.SetValidValue(value, true, "designation");
                ReportPropertyChanged("designation");
                OndesignationChanged();
            }
        }
        private global::System.String _designation;
        partial void OndesignationChanging(global::System.String value);
        partial void OndesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String branch
        {
            get
            {
                return _branch;
            }
            set
            {
                OnbranchChanging(value);
                ReportPropertyChanging("branch");
                _branch = StructuralObject.SetValidValue(value, true, "branch");
                ReportPropertyChanged("branch");
                OnbranchChanged();
            }
        }
        private global::System.String _branch;
        partial void OnbranchChanging(global::System.String value);
        partial void OnbranchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> contact_no
        {
            get
            {
                return _contact_no;
            }
            set
            {
                Oncontact_noChanging(value);
                ReportPropertyChanging("contact_no");
                _contact_no = StructuralObject.SetValidValue(value, "contact_no");
                ReportPropertyChanged("contact_no");
                Oncontact_noChanged();
            }
        }
        private Nullable<global::System.Int32> _contact_no;
        partial void Oncontact_noChanging(Nullable<global::System.Int32> value);
        partial void Oncontact_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lectures
        {
            get
            {
                return _lectures;
            }
            set
            {
                OnlecturesChanging(value);
                ReportPropertyChanging("lectures");
                _lectures = StructuralObject.SetValidValue(value, true, "lectures");
                ReportPropertyChanged("lectures");
                OnlecturesChanged();
            }
        }
        private global::System.String _lectures;
        partial void OnlecturesChanging(global::System.String value);
        partial void OnlecturesChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCC_DOTNET_LMSModel", "fk_loginid", "tblTeacherLogin")]
        public tblTeacherLogin tblTeacherLogin
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTeacherLogin>("BCC_DOTNET_LMSModel.fk_loginid", "tblTeacherLogin").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTeacherLogin>("BCC_DOTNET_LMSModel.fk_loginid", "tblTeacherLogin").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblTeacherLogin> tblTeacherLoginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTeacherLogin>("BCC_DOTNET_LMSModel.fk_loginid", "tblTeacherLogin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblTeacherLogin>("BCC_DOTNET_LMSModel.fk_loginid", "tblTeacherLogin", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCC_DOTNET_LMSModel", Name="tblTeacherLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTeacherLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTeacherLogin object.
        /// </summary>
        /// <param name="loginid">Initial value of the loginid property.</param>
        public static tblTeacherLogin CreatetblTeacherLogin(global::System.Int32 loginid)
        {
            tblTeacherLogin tblTeacherLogin = new tblTeacherLogin();
            tblTeacherLogin.loginid = loginid;
            return tblTeacherLogin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 loginid
        {
            get
            {
                return _loginid;
            }
            set
            {
                if (_loginid != value)
                {
                    OnloginidChanging(value);
                    ReportPropertyChanging("loginid");
                    _loginid = StructuralObject.SetValidValue(value, "loginid");
                    ReportPropertyChanged("loginid");
                    OnloginidChanged();
                }
            }
        }
        private global::System.Int32 _loginid;
        partial void OnloginidChanging(global::System.Int32 value);
        partial void OnloginidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCC_DOTNET_LMSModel", "fk_loginid", "tblTeacherInfo")]
        public tblTeacherInfo tblTeacherInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTeacherInfo>("BCC_DOTNET_LMSModel.fk_loginid", "tblTeacherInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTeacherInfo>("BCC_DOTNET_LMSModel.fk_loginid", "tblTeacherInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblTeacherInfo> tblTeacherInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTeacherInfo>("BCC_DOTNET_LMSModel.fk_loginid", "tblTeacherInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblTeacherInfo>("BCC_DOTNET_LMSModel.fk_loginid", "tblTeacherInfo", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BCC_DOTNET_LMSModel", Name="sp_searchBooks_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_searchBooks_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp_searchBooks_Result object.
        /// </summary>
        /// <param name="code">Initial value of the code property.</param>
        public static sp_searchBooks_Result Createsp_searchBooks_Result(global::System.Int32 code)
        {
            sp_searchBooks_Result sp_searchBooks_Result = new sp_searchBooks_Result();
            sp_searchBooks_Result.code = code;
            return sp_searchBooks_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code
        {
            get
            {
                return _code;
            }
            set
            {
                OncodeChanging(value);
                ReportPropertyChanging("code");
                _code = StructuralObject.SetValidValue(value, "code");
                ReportPropertyChanged("code");
                OncodeChanged();
            }
        }
        private global::System.Int32 _code;
        partial void OncodeChanging(global::System.Int32 value);
        partial void OncodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, true, "author");
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String publication
        {
            get
            {
                return _publication;
            }
            set
            {
                OnpublicationChanging(value);
                ReportPropertyChanging("publication");
                _publication = StructuralObject.SetValidValue(value, true, "publication");
                ReportPropertyChanged("publication");
                OnpublicationChanged();
            }
        }
        private global::System.String _publication;
        partial void OnpublicationChanging(global::System.String value);
        partial void OnpublicationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String subject
        {
            get
            {
                return _subject;
            }
            set
            {
                OnsubjectChanging(value);
                ReportPropertyChanging("subject");
                _subject = StructuralObject.SetValidValue(value, true, "subject");
                ReportPropertyChanged("subject");
                OnsubjectChanged();
            }
        }
        private global::System.String _subject;
        partial void OnsubjectChanging(global::System.String value);
        partial void OnsubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> no_of_copies
        {
            get
            {
                return _no_of_copies;
            }
            set
            {
                Onno_of_copiesChanging(value);
                ReportPropertyChanging("no_of_copies");
                _no_of_copies = StructuralObject.SetValidValue(value, "no_of_copies");
                ReportPropertyChanged("no_of_copies");
                Onno_of_copiesChanged();
            }
        }
        private Nullable<global::System.Int32> _no_of_copies;
        partial void Onno_of_copiesChanging(Nullable<global::System.Int32> value);
        partial void Onno_of_copiesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] cover_pic
        {
            get
            {
                return StructuralObject.GetValidValue(_cover_pic);
            }
            set
            {
                Oncover_picChanging(value);
                ReportPropertyChanging("cover_pic");
                _cover_pic = StructuralObject.SetValidValue(value, true, "cover_pic");
                ReportPropertyChanged("cover_pic");
                Oncover_picChanged();
            }
        }
        private global::System.Byte[] _cover_pic;
        partial void Oncover_picChanging(global::System.Byte[] value);
        partial void Oncover_picChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion

    }

    #endregion

}
